### ISSUE TITLE
 The user shall be limited to seven expense categories and four income categories

### ISSUE THREAD

**Issue by nahidul-islamm** [WSU-4110/Budget-Minimalism#3]
|NFR1. The user shall be limited to seven expense categories and four income categories|
|---|
|**Goal**: Limiting the number of categories will help keep users focused
**Stakeholders:** Users|
| **Description:** The user will be able to fill in the categories for expenses and incomes .|
| **Origin:**   Initial project vision originates from the planning process and brainstorming  |  
| **Version:** 1.0  |  
|**Date:** 09/17/2019  
|  **Priority:** 1 |

**Comment by Mohammed-Rahin** [comment]
Done
